version: '3.8'

services:
  my-cms:
    build:
      context: ./DeployedCms 
      dockerfile: Dockerfile
    
    container_name: cms_apache
    restart: unless-stopped
    volumes:
      - /opt/cms-app:/var/www/cms 
  proxy-manager:
    image: jlesage/nginx-proxy-manager:v26.05.1
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - "80:8080"   
      - "443:4443"  
      - "81:8181"   
    volumes:
      - ./npm/config:/config